# Generated by Django 3.0.6 on 2020-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20200514_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadim',
            name='vid',
            field=models.CharField(choices=[('LS', 'Личное сообщение'), ('GR', 'Групповое сообщение')], default='LS', max_length=2),
        ),
    ]
