# Generated by Django 3.0.6 on 2020-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_threadim_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='Invitation',
            field=models.ManyToManyField(to='messenger.Invitation'),
        ),
    ]
