# Generated by Django 3.0.6 on 2020-05-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20200524_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Invitation',
            new_name='invitation',
        ),
    ]
