# Generated by Django 3.0.6 on 2020-05-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20200529_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='team',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.Team'),
        ),
    ]
