# Generated by Django 3.0.6 on 2020-05-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20200529_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lider',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messenger.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='invitation',
            field=models.ManyToManyField(blank=True, to='messenger.Invitation'),
        ),
    ]
